// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class MethodChannelMessagesPigeonCodecReader: FlutterStandardReader {
}

private class MethodChannelMessagesPigeonCodecWriter: FlutterStandardWriter {
}

private class MethodChannelMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MethodChannelMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MethodChannelMessagesPigeonCodecWriter(data: data)
  }
}

class MethodChannelMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MethodChannelMessagesPigeonCodec(readerWriter: MethodChannelMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MacOSMessageApi {
  func writeFile(fileName: String, bytes: FlutterStandardTypedData, completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MacOSMessageApiSetup {
  static var codec: FlutterStandardMessageCodec { MethodChannelMessagesPigeonCodec.shared }
  /// Sets up an instance of `MacOSMessageApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MacOSMessageApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let writeFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_file_manager_macos.MacOSMessageApi.writeFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fileNameArg = args[0] as! String
        let bytesArg = args[1] as! FlutterStandardTypedData
        api.writeFile(fileName: fileNameArg, bytes: bytesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeFileChannel.setMessageHandler(nil)
    }
  }
}
